import GethIPC from './GethIPC';
import IpfsIPC from './IpfsIPC';
import AuthIPC from './AuthIPC';
import TxIPC from './TxIPC';
import RegistryIPC from './RegistryIPC';
import ProfileIPC from './ProfileIPC';
import TagsIPC from './TagsIPC';
import EntryIPC from './EntryIPC';
import CommentsIPC from './CommentsIPC';
import LicensesIPC from './LicensesIPC';
import NotificationsIPC from './NotificationsIPC';
import ChatIPC from './ChatIPC';
import SearchIPC from './SearchIPC';
import UtilsIPC from './UtilsIPC';
declare const _default: (GethIPC | IpfsIPC | AuthIPC | TxIPC | RegistryIPC | ProfileIPC | TagsIPC | EntryIPC | CommentsIPC | LicensesIPC | NotificationsIPC | ChatIPC | SearchIPC | UtilsIPC)[];
export default _default;
